# Built from native speakers, with inspiration from
# https://github.com/zacanger/profane-words
# and
# https://github.com/thisandagain/washyourmouthoutwithsoap/blob/develop/data/build.json
# and
# https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words


english_flagged_words = [
    "anal",
    "bareback",
    "bbw",
    "bdsm",
    "blowjob",
    "blowjobs",
    "brazzers",
    "bukkake",
    "camgirl",
    "camwhore",
    "cocksucking",
    "cougar",
    "creampie",
    "cuckold",
    "cum",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cunnilingus",
    "deepthroat",
    "deepthroating",
    "dildo",
    "dildos",
    "dogging",
    "doggystyle",
    "dominatrix",
    "erotic",
    "fellatio",
    "femdom",
    "fingering",
    "fisting",
    "footjob",
    "gangbang",
    "handjob",
    "hentai",
    "horney",
    "horniest",
    "horny",
    "jism",
    "jizz",
    "masterbating",
    "masturbate",
    "masturbating",
    "masturbation",
    "milf",
    "orgies",
    "orgy",
    "pegging",
    "porn",
    "pornhub",
    "porno",
    "pornos",
    "pornstar",
    "pornstars",
    "redtube",
    "rimming",
    "slutty",
    "squirting",
    "strapon",
    "threesome",
    "vibrator",
    "xhamster",
    "xnxx",
    "xvideos",
    "xxx",
    "youporn",
]

flagged_words = {
    "en": english_flagged_words,
    "vi": english_flagged_words
    + [
        '4`',
        'an lol',
        'an lon',
        'b`',
        'banh háng',
        'banh lol',
        'banh lon',
        'bitch',
        'biz',
        'bo me',
        'bo mia',
        'bo mie',
        'bo mja',
        'bo mje',
        'bucak',
        'buoi',
        'buscu',
        'buồi',
        'bà cha mày',
        'bít chi',
        'bòi',
        'bú buoi',
        'bú cac',
        'bú cak',
        'bú cax',
        'bú cu',
        'bú cặc',
        'bú lol',
        'bú lon',
        'bú lồn',
        'bú mút',
        'bướm non',
        'bỏ bú',
        'bỏ mja',
        'bỏ mje',
        'bỏ mẹ',
        'bỏ mịa',
        'bỏ mịe',
        'bố láo',
        'cac',
        'cai lol',
        'cai lon',
        'caiconcac',
        'caiconcak',
        'caidauboi',
        'caidauboy',
        'caidaubuoi',
        'cailon',
        'cak',
        'cao lol',
        'cao lon',
        'cdi~',
        'chet me',
        'chet mia',
        'chet mie',
        'chet mja',
        'chet mje',
        'chetme',
        'chich',
        'chich choac',
        'chó má',
        'chó điên',
        'chết mie',
        'chết mja',
        'chết mẹ',
        'chết mịa',
        'chết mịe',
        'chịch',
        'chịch kiểu chó',
        'chịch lén',
        'chịch lỗ đít',
        'chịch tập thể',
        'chổng mông',
        'cl',
        'clgt',
        'cmn',
        'cmnl',
        'con bic',
        'con bíc',
        'con bích',
        'con bít',
        'con di cho',
        "con di cho'",
        'con lol',
        'con lon',
        'concak',
        'condi',
        'condicho',
        'condimay',
        'condime',
        'condimemay',
        'condi~',
        'cu',
        'cu lol',
        'cu lon',
        'cuccut',
        'cuk',
        'cutcut',
        'cào lol',
        'cào lon',
        'cái lol',
        'cái lon',
        'cái lề gì thốn',
        'cái lờ',
        'cđĩ',
        'cười ẻ',
        'cười ỉa',
        'cặc',
        'cặk',
        'cờ hó',
        'cờ lờ gờ tờ',
        'củ lol',
        'củ lon',
        'cứk',
        'cứt',
        "d'",
        'dach lol',
        'dach lon',
        'dau boi',
        'dau boy',
        'dau buoi',
        'dauboi',
        'dauboy',
        'daubuoi',
        'dcm',
        'dcmm',
        'dcmmm',
        'dcmmmm',
        'dech',
        'dek',
        'del',
        'dell an',
        'dell biet',
        'dell biết',
        'dell chay',
        'dell chiu',
        'dell chạy',
        'dell chịu',
        'dell di',
        'dell duoc',
        'dell hieu',
        'dell hiểu',
        'dell lam',
        'dell làm',
        'dell nghe',
        'dell ngui',
        'dell ngửi',
        'dell noi',
        'dell nói',
        'dell ăn',
        'dell đi',
        'dell được',
        'dellhieukieugi',
        'dellnoinhieu',
        'deo',
        'deohieukieugi',
        'di me',
        'dilol',
        'dilon',
        'diloz',
        'dime',
        'dimemay',
        'diml',
        'dis',
        'dis me',
        'dis mia',
        'dis mie',
        'disme',
        'dismia',
        'dismje',
        'dit',
        'ditmeconcho',
        'ditmecondi',
        'ditmecondicho',
        'ditmemay',
        'ditmemayconcho',
        'ditmethangoccho',
        'diz',
        'di~',
        'djt',
        'dm',
        'dmconcho',
        'dmcs',
        'dml',
        'dmm',
        'dmmm',
        'dmmmm',
        'dmmmmm',
        'doma',
        'dou',
        'dou ma',
        'dou má',
        'duo má',
        'duoma',
        'dái',
        'fck',
        'fuck',
        'giái',
        'ham lol',
        'ham lon',
        'hãm',
        'húp lol',
        'húp lon',
        'húp sò',
        'kac',
        'kak',
        'ke me',
        'ke mia',
        'ke mie',
        'ke mja',
        'ke mje',
        'kiu',
        'kệ mja',
        'kệ mje',
        'kệ mẹ',
        'kệ mịa',
        'kệ mịe',
        'l`',
        'la liếm',
        'lao cho',
        'loi lol',
        'loi lon',
        'lol non',
        'lon to',
        'loz',
        'láo chó',
        'lìn',
        'lòi lol',
        'lòi lon',
        'lồn',
        'lồn múp',
        'ma cha may',
        'ma cha nha may',
        'mat lol',
        'mat lon',
        'matlol',
        'matlon',
        'matloz',
        'me cha may',
        'me cha nha may',
        'ml',
        'mom lol',
        'mom lon',
        'mu lol',
        'mu lon',
        'mát lol',
        'mát lon',
        'móc lol',
        'móc lon',
        'mõm lol',
        'mõm lon',
        'mả cha',
        'mả cha mày',
        'mả cha nhà mày',
        'mả mẹ',
        'mặt lol',
        'mặt lon',
        'mẹ bà',
        'mẹ cha anh',
        'mẹ cha mày',
        'mẹ cha nhà anh',
        'mẹ cha nhà mày',
        'mồm lol',
        'mồm lon',
        'ngu',
        'ngu lol',
        'ngu lon',
        'nhu lol',
        'nhu lon',
        'nhucaidaubuoi',
        'như lol',
        'như lon',
        'nug',
        'nug lol',
        'nug lon',
        'nuglol',
        'nuglon',
        'nulo',
        'nung buoi',
        'nung cac',
        'nung lol',
        'nung lon',
        'nungcak',
        'nốn lừng',
        'nứng',
        'nứng lol',
        'nứng lon',
        'nứng lồn',
        'occho',
        'phim sex',
        'phim xex',
        'phim xxx',
        'phò',
        'ranh lol',
        'ranh lon',
        'rảnh lol',
        'rảnh lon',
        'sap mat',
        'sapmatlol',
        'sapmatlon',
        'sapmatloz',
        'sml',
        'sảng',
        'sấp mặt',
        'sủa bậy',
        'sủa càn',
        'sủa tiếp',
        'sủa đi',
        'tet lol',
        'tet lon',
        'thang cho',
        "thang cho'",
        'thang dien',
        'thangmatlon',
        'thangml',
        'thay me',
        'thay mia',
        'thay mie',
        'thml',
        'thèm buoi',
        'thèm cak',
        'thèm cax',
        'thèm chich',
        'thèm chịch',
        'thèm dit',
        'thèm dit',
        'thèm lol',
        'thèm lon',
        'thấy mẹ',
        'thấy mịa',
        'thấy mịe',
        'thằng chó',
        'thằng điên',
        'tiên sư bố',
        'tiên sư nhà mày',
        'tml',
        'tung lol',
        'tung lon',
        'tuoi lol',
        'tuoi lon',
        'tuổi lol',
        'tuổi lon',
        'tét lol',
        'tét lon',
        'tổ cha',
        'tổ sư',
        'vach lol',
        'vach lon',
        'vai lol',
        'vai lon',
        'vailol',
        'vailon',
        'vcl',
        'vl',
        'vleu',
        'vlol',
        'vlon',
        'vloz',
        'v~',
        'vãi',
        'vú bự',
        'vú to',
        'vạch lol',
        'vạch lon',
        'xam lol',
        'xam lon',
        'xao lol',
        'xao lon',
        'xephinh',
        'xhct',
        'xoac',
        'xoạc',
        'xàm lol',
        'xàm lon',
        'xéo háng',
        'xạo lol',
        'xạo lon',
        'zái',
        'á đìu',
        'á đù',
        'óc chó',
        'ăn lol',
        'ăn lon',
        "đ'",
        'đcm',
        'đcmm',
        'đcmmm',
        'đcmmmm',
        'đel',
        'đilol',
        'đilon',
        'điloz',
        'đis mịa',
        'đis mịe',
        'điếm',
        'đjt',
        'đm',
        'đmm',
        'đmmm',
        'đmmmm',
        'đmmmmm',
        'đou má',
        'đuỹ',
        'đách',
        'đách lol',
        'đách lon',
        'đél',
        'đéo',
        'đê ma ma',
        'đê mama',
        'đê mờ',
        'đìu',
        'đìu má',
        'đù cha',
        'đù má',
        'đù mẹ',
        'đù mịa',
        'đù mịe',
        'đú cha',
        'đú con mẹ',
        'đú má',
        'đú mẹ',
        'đút đít',
        'đĩ',
        'đầu bòy',
        'đầu bùi',
        'đậu má',
        'đậu mẹ',
        'đếch',
        'đếk',
        'đết',
        'đề ma ma',
        'đề mama',
        'đệch',
        'đệt',
        'địt',
        'địt ba',
        'địt bà',
        'địt bố',
        'địt cha',
        'địt con',
        'địt cụ',
        'địt má',
        'địt mía',
        'địt mẹ',
        'địt mịe',
        'đốn cửa lòng',
        'đồ điên',
        'đổ vỏ',
        'đỗn lì',
        'đờ ma ma',
        'đờ mama',
        'đờ mờ',
        'đụ',
        'đụ bà',
        'đụ cha',
        'đụ má',
        'đụ mẹ',
        'đụ mịa',
        'đụ mịe',
        'đủ cha',
        'đủ mia',
        'đủ mie',
        'đủ má',
        'đủ mé',
        'đủ mía',
        'đủ mẹ',
        'đủ mịa',
        'đủ mịe',
    ]
}
