# Built from native speakers, with inspiration from
# https://github.com/6/stopwords-json
# and
# https://github.com/stopwords-iso/stopwords-iso for Urdu and Vietnamese


stopwords = {
    "en": [
        "a",
        "a.k.a",
        "aboard",
        "about",
        "above",
        "abt",
        "accord",
        "according",
        "across",
        "after",
        "against",
        "ago",
        "aground",
        "ahead",
        "aka",
        "ala",
        "albeit",
        "all",
        "along",
        "alongside",
        "although",
        "am",
        "amid",
        "amidst",
        "among",
        "amongst",
        "amoung",
        "an",
        "and",
        "and/or",
        "another",
        "any",
        "any1",
        "anybody",
        "anyone",
        "anything",
        "are",
        "around",
        "as",
        "aside",
        "astride",
        "at",
        "atop",
        "away",
        "b",
        "b/c",
        "b/t",
        "back",
        "base",
        "based",
        "bc",
        "be",
        "because",
        "been",
        "before",
        "behind",
        "being",
        "below",
        "beneath",
        "beside",
        "besides",
        "between",
        "beyond",
        "board",
        "both",
        "btwn",
        "but",
        "by",
        "can",
        "cause",
        "circa",
        "cos",
        "could",
        "coz",
        "cus",
        "depend",
        "depending",
        "despite",
        "did",
        "do",
        "does",
        "down",
        "due",
        "during",
        "each",
        "either",
        "else",
        "even",
        "ever",
        "every",
        "everybody",
        "everyone",
        "everything",
        "except",
        "for",
        "forth",
        "from",
        "get",
        "gets",
        "getting",
        "give",
        "given",
        "got",
        "had",
        "half",
        "has",
        "hav",
        "have",
        "having",
        "he",
        "her",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "how",
        "however",
        "i",
        "i'd",
        "if",
        "in",
        "include",
        "including",
        "inside",
        "instead",
        "into",
        "is",
        "it",
        "it's",
        "its",
        "itself",
        "lest",
        "like",
        "made",
        "many",
        "may",
        "me",
        "might",
        "mine",
        "minus",
        "most",
        "much",
        "must",
        "my",
        "myself",
        "nary",
        "near",
        "nearby",
        "neither",
        "next",
        "nigh",
        "no",
        "nobody",
        "none",
        "noone",
        "nor",
        "not",
        "nothing",
        "notwithstanding",
        "of",
        "off",
        "on",
        "onboard",
        "once",
        "one",
        "ones",
        "oneself",
        "only",
        "onto",
        "opposite",
        "or",
        "other",
        "others",
        "ought",
        "our",
        "ours",
        "ourselves",
        "out",
        "outside",
        "over",
        "overt",
        "own",
        "past",
        "per",
        "plus",
        "prior",
        "quite",
        "rather",
        "re",
        "regard",
        "regarding",
        "regardless",
        "round",
        "s/he",
        "save",
        "self",
        "shall",
        "she",
        "should",
        "side",
        "since",
        "so",
        "some",
        "somebody",
        "someone",
        "something",
        "such",
        "sure",
        "teh",
        "than",
        "thanks",
        "that",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "there",
        "these",
        "they",
        "they're",
        "thier",
        "this",
        "tho",
        "those",
        "thou",
        "though",
        "through",
        "throughout",
        "thru",
        "thy",
        "til",
        "till",
        "to",
        "together",
        "too",
        "toward",
        "towards",
        "u",
        "under",
        "underneath",
        "unless",
        "unlike",
        "until",
        "unto",
        "up",
        "upon",
        "ur",
        "us",
        "use",
        "versus",
        "via",
        "vs",
        "vs.",
        "w/",
        "w/o",
        "w/out",
        "was",
        "we",
        "were",
        "what",
        "whatever",
        "whatnot",
        "when",
        "whenever",
        "where",
        "whereas",
        "wherever",
        "whether",
        "which",
        "while",
        "whilst",
        "whither",
        "who",
        "who's",
        "whoever",
        "whom",
        "whomever",
        "whose",
        "why",
        "will",
        "with",
        "within",
        "without",
        "wo",
        "worth",
        "would",
        "wud",
        "y'all",
        "ya",
        "yet",
        "yo",
        "you",
        "you're",
        "your",
        "youre",
        "yours",
        "yourself",
        "yourselves",
    ],
    "vi": [
        "ai",
        "ai ai",
        "ai nấy",
        "anh",
        "anh em",
        "anh trai",
        "anh ấy",
        "ba",
        "bao",
        "bao giờ",
        "bay",
        "bà",
        "bà con",
        "bà ấy",
        "bác",
        "bây",
        "bé",
        "bên",
        "bạn",
        "bạn gái",
        "bạn trai",
        "bả",
        "bản thân",
        "bất chấp",
        "bất cứ",
        "bất kì",
        "bất luận",
        "bất nhược",
        "bất quá",
        "bấy",
        "bấy nhiêu",
        "bần tăng",
        "bầy quân",
        "bầy tui",
        "bậu",
        "bằng",
        "bệ hạ",
        "bị cáo",
        "bố",
        "bố nó",
        "bồ",
        "bộ",
        "bởi",
        "bởi vì",
        "cc",
        "cha",
        "chao",
        "chi",
        "chiếu theo",
        "cho",
        "cho dù",
        "cho đến",
        "choa",
        "chàng",
        "chán",
        "cháu",
        "chí",
        "chính",
        "chú",
        "chú mày",
        "chúng",
        "chúng mày",
        "chúng mình",
        "chúng nó",
        "chúng ta",
        "chúng tao",
        "chúng tôi",
        "chút",
        "chăng",
        "chưa",
        "chưng",
        "chả",
        "chắc",
        "chẳng cứ",
        "chỉ",
        "chị",
        "chị gái",
        "chị ấy",
        "chớ",
        "chứ",
        "con",
        "con này",
        "cuối cùng",
        "các",
        "các hạ",
        "cái",
        "cái gì",
        "cái này",
        "cán bộ",
        "còn",
        "có",
        "có vẻ",
        "cóc",
        "cô",
        "cô nương",
        "cô ta",
        "cô ấy",
        "côi",
        "công tử",
        "cùng",
        "cơ",
        "cơ mà",
        "cưng",
        "cạnh",
        "cả",
        "cả nhà",
        "cầm bằng",
        "cậu",
        "cổ",
        "cộng",
        "cụ",
        "của",
        "cứ",
        "do",
        "do vậy",
        "do đó",
        "duy",
        "dù",
        "dù sao",
        "dù vậy",
        "dưng",
        "dưới",
        "dường như",
        "dạ",
        "dầu",
        "dẫu",
        "dẫu vậy",
        "dậy",
        "dọc",
        "dợ",
        "em",
        "ghe",
        "già",
        "giá như",
        "giả dụ",
        "giả sử",
        "giữa",
        "gì",
        "ha",
        "hay",
        "hay là",
        "hen",
        "hoàng thượng",
        "hoặc",
        "huynh",
        "huống",
        "huống chi",
        "huống gì",
        "huống hồ",
        "há",
        "hôn",
        "hơn",
        "hơn nữa",
        "hả",
        "hầu hết",
        "hắn",
        "hết",
        "hết cả",
        "hề",
        "hễ",
        "họ",
        "hổi",
        "hỡi",
        "hử",
        "khanh",
        "khi",
        "khi nào",
        "không",
        "không ai",
        "không những",
        "khứa",
        "kia",
        "kém",
        "kìa",
        "kẻo",
        "kể từ",
        "l",
        "là",
        "lão",
        "lên",
        "lại nữa",
        "lần",
        "lẫn",
        "lắm",
        "mi",
        "min",
        "miễn",
        "moa",
        "muôn",
        "muội",
        "mà",
        "mà còn",
        "mày",
        "mãi",
        "mình",
        "mô",
        "mũ",
        "mất",
        "mấy",
        "mầy",
        "mẫu hậu",
        "mặc dù",
        "mặc dầu",
        "mặt khác",
        "mẹ",
        "mẹ nó",
        "mọi",
        "mọi người",
        "mọi vật",
        "mỏa",
        "mỗi",
        "một chút",
        "một nửa",
        "một số",
        "một vài",
        "một ít",
        "mụ",
        "ngay",
        "nghe",
        "nghen",
        "nghỉ",
        "ngoài",
        "ngoài ra",
        "ngoại",
        "ngoải",
        "ngài",
        "ngươi",
        "người",
        "người người",
        "người ta",
        "ngược lại",
        "ngộ",
        "nha",
        "nhiều",
        "nhà quân",
        "nhá",
        "nhân",
        "nhân dịp",
        "nhé",
        "như",
        "như vậy",
        "nhưng",
        "nhưng mà",
        "nhược bằng",
        "nhất là",
        "nhằm",
        "nhỉ",
        "nhỏ",
        "nhờ",
        "nhỡ",
        "những",
        "ni",
        "nà",
        "nàng",
        "nào",
        "này",
        "nè",
        "nên",
        "nó",
        "nô tài",
        "nô tì",
        "nơi",
        "nơi nơi",
        "nấy",
        "nầy",
        "nẩu",
        "nếu",
        "nếu như",
        "nọ",
        "nội",
        "nớ",
        "nừng",
        "nửa",
        "nữa",
        "phi",
        "phía",
        "phô bay",
        "phải",
        "phải hôn",
        "phải không",
        "phần",
        "phần lớn",
        "phỏng",
        "phứt",
        "qua",
        "quanh",
        "quý khách",
        "quý vị",
        "quả",
        "quả nhân",
        "ra",
        "riêng",
        "rùi",
        "rằng",
        "rồi",
        "sang",
        "sao",
        "sau",
        "sau cùng",
        "song",
        "song le",
        "sắp",
        "sẽ",
        "sở dĩ",
        "ta",
        "tao",
        "tau",
        "thanh niên",
        "thay",
        "thay vì",
        "theo",
        "theo đó",
        "thiếp",
        "thiệt",
        "thành",
        "thâu",
        "thêm",
        "thì",
        "thí dụ",
        "thôi",
        "thần",
        "thầy",
        "thẩy",
        "thật",
        "thằng này",
        "thế",
        "thế là",
        "thế mà",
        "thế nhưng",
        "thị",
        "thời",
        "tiểu nhân",
        "toa",
        "toà",
        "toàn",
        "toàn bộ",
        "toàn thể",
        "trong",
        "trong khi",
        "trong đó",
        "trái",
        "trái lại",
        "trên",
        "trò",
        "trước",
        "trẫm",
        "trời",
        "trừ phi",
        "tuy",
        "tuy nhiên",
        "tuy rằng",
        "tuy vậy",
        "tê",
        "tóm lại",
        "tôi",
        "tương đương",
        "tại",
        "tại hạ",
        "tại vì",
        "tất cả",
        "tầm",
        "tận",
        "tỉ",
        "tổ",
        "tớ",
        "tới",
        "tụi",
        "tụi nó",
        "tức",
        "tức là",
        "từ",
        "tự",
        "tựa",
        "ui",
        "và",
        "vài",
        "vài ba",
        "vào",
        "vì",
        "vì thế",
        "vì vậy",
        "ví dụ",
        "ví như",
        "vô",
        "vô số",
        "vô vàn",
        "vả chăng",
        "vả lại",
        "vậy",
        "vậy là",
        "vậy mà",
        "về",
        "về hướng",
        "về phía",
        "vị",
        "với",
        "xuống",
        "à",
        "á",
        "ái khanh",
        "âu là",
        "í",
        "ít",
        "ông",
        "ông ấy",
        "út",
        "ý",
        "đa số",
        "đang",
        "đi",
        "đâu",
        "đây",
        "đã",
        "đê",
        "đích thân",
        "đó",
        "đôi",
        "đương",
        "được",
        "đại nhân",
        "đấy",
        "đầu tiên",
        "đằng này",
        "đằng ấy",
        "đẳng",
        "đặng",
        "đến",
        "để",
        "đệ",
        "đối với",
        "đồ",
        "ơi",
        "ư",
        "ạ",
        "ả",
        "ảnh",
        "ấy",
        "ẻm",
        "ổng",
        "ờ",
        "ở",
        "ừ",
        "ừa",
        "ừm",
    ],
}
